device: "cuda"
save_dir_plots: "plots"
save_dir_model: "models"
save_dir_predictions: "predictions"
model_name: "final_model.pth"
train_idx_path: "indices/train.parquet"
val_idx_path: "indices/val.parquet"
test_idx_path: "indices/test.parquet"
